apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-storage-claim
  name: minio-pv-claim
  namespace: tracing-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
